#!/usr/bin/env python3
"""
PhoneHub pipeline — STAGE 4: build js/data.js
========================================================================
Merges the three caches into the single file the static site reads:
    data/specs.json   (stage 1)  +
    data/content.json (stage 2)  +
    data/prices.json  (stage 3)  ->  ../js/data.js

USAGE:  python build.py
Stdlib only.
========================================================================
"""
import json
import os
import re

import ph_common as C

# drop lifestyle / in-hand / review images; keep clean product shots only
_BAD_IMG = re.compile(r"/reviews/|lifestyle|gsmarena_\d|in-hand|hands-on|-hand", re.I)


def product_images(imgs):
    return [u for u in (imgs or []) if u and not _BAD_IMG.search(u)]

DEFAULT_NEWS = [
    {"id": "n1", "title": "How we rate phones", "excerpt": "Our reviews are generated from verified specifications and updated automatically.", "date": "2024-07-01", "tag": "Editorial"},
]


def enrich_brands(brands):
    """Enrich brand data with logos, colors, and categories from BRAND_DATABASE."""
    enriched = []
    for brand in brands:
        brand_id = brand.get("id", "")
        brand_data = C.BRAND_DATABASE.get(brand_id, {})
        
        enriched_brand = {
            "id": brand_id,
            "name": brand.get("name", brand_id.title()),
            "logo": brand_data.get("logo", brand.get("logo", "📱")),
            "color": brand_data.get("color", "#5b8cff"),
            "category": brand_data.get("category", "Other")
        }
        enriched.append(enriched_brand)
    
    return enriched


def main():
    specs = C.read_json("specs.json")
    if not specs:
        raise SystemExit("data/specs.json missing. Run import_specs.py first.")
    content = C.read_json("content.json", default={})
    prices = C.read_json("prices.json", default={})
    news = C.read_json("news.json", default=DEFAULT_NEWS)
    
    # Enrich brand data with logos and categories
    enriched_brands = enrich_brands(specs.get("brands", []))

    import gen_images
    merged = []
    for p in specs["phones"]:
        cid = p["id"]
        c = content.get(cid, {})
        pr = prices.get(cid, {})
        popularity = c.get("popularity", 55)
        rating = c.get("rating", 0)
        imgs = product_images(p.get("images", []))
        if imgs:
            p["image"] = imgs[0]
        image, fallback = gen_images.resolve(p)
        merged.append({
            "id": cid,
            "brand": p["brand"],
            "name": p["name"],
            "category": p.get("category", "phone"),
            "image": image,
            "images": imgs,
            "fallbackImg": fallback,
            "releaseDate": p.get("releaseDate", ""),
            "basePrice": pr.get("basePrice", 0),
            "popularity": popularity,
            "rating": rating,
            "reviewCount": int(popularity * 12) if rating else 0,
            "review": c.get("review", ""),
            "quickSpecs": p.get("quickSpecs", {}),
            "prices": pr.get("prices", []),
            "pros": c.get("pros", []),
            "cons": c.get("cons", []),
            "specs": p.get("specs", {}),
        })

    # merged.json is the clean source the prerenderer reads
    C.write_json("merged.json", {"brands": enriched_brands, "phones": merged, "news": news})

    # lightweight index (loaded on every page) — full 'specs' & 'images' stripped
    lite = [{k: v for k, v in m.items() if k not in ("specs", "images")} for m in merged]
    specs_map = {m["id"]: m.get("specs", {}) for m in merged}

    out_path = os.path.join(C.HERE, "..", "js", "data.js")
    lines = [
        "/* AUTO-GENERATED by the PhoneHub pipeline (tools/build.py). Do not edit by hand. */",
        "window.BRANDS = " + json.dumps(enriched_brands, ensure_ascii=False, indent=2) + ";",
        'window.STORES = ["Amazon", "Flipkart", "Croma", "Reliance Digital", "Official Store"];',
        "window.PHONES = " + json.dumps(lite, ensure_ascii=False) + ";",
        "window.NEWS = " + json.dumps(news, ensure_ascii=False, indent=2) + ";",
    ]
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    # full specs live in a separate file, loaded only by the compare page
    specs_path = os.path.join(C.HERE, "..", "js", "specs-data.js")
    with open(specs_path, "w", encoding="utf-8") as f:
        f.write("/* AUTO-GENERATED specs map for the compare page. */\n")
        f.write("window.SPECS = " + json.dumps(specs_map, ensure_ascii=False) + ";\n")

    priced = sum(1 for m in merged if m["basePrice"])
    reviewed = sum(1 for m in merged if m["rating"])
    print(f"[build] wrote js/data.js — {len(merged)} phones "
          f"({reviewed} with AI reviews, {priced} with live prices)")

    # pre-render static pages, regenerate sitemap/robots, then ping IndexNow
    for mod_name in ("prerender", "gen_seo", "indexnow"):
        try:
            mod = __import__(mod_name)
            mod.main()
        except SystemExit:
            pass
        except Exception as e:  # noqa
            print(f"[build] {mod_name} skipped: {e}")


if __name__ == "__main__":
    main()
