#!/usr/bin/env python3
"""
PhoneHub pipeline — STAGE 4: build js/data.js
========================================================================
Merges the three caches into the single file the static site reads:
    data/specs.json   (stage 1)  +
    data/content.json (stage 2)  +
    data/prices.json  (stage 3)  ->  ../js/data.js

USAGE:  python build.py
Stdlib only.
========================================================================
"""
import json
import os

import ph_common as C

DEFAULT_NEWS = [
    {"id": "n1", "title": "How we rate phones", "excerpt": "Our reviews are generated from verified specifications and updated automatically.", "date": "2024-07-01", "tag": "Editorial"},
]


def main():
    specs = C.read_json("specs.json")
    if not specs:
        raise SystemExit("data/specs.json missing. Run import_specs.py first.")
    content = C.read_json("content.json", default={})
    prices = C.read_json("prices.json", default={})
    news = C.read_json("news.json", default=DEFAULT_NEWS)

    import gen_images
    merged = []
    for p in specs["phones"]:
        cid = p["id"]
        c = content.get(cid, {})
        pr = prices.get(cid, {})
        popularity = c.get("popularity", 55)
        rating = c.get("rating", 0)
        image, fallback = gen_images.resolve(p)
        merged.append({
            "id": cid,
            "brand": p["brand"],
            "name": p["name"],
            "image": image,
            "images": p.get("images", []),
            "fallbackImg": fallback,
            "releaseDate": p.get("releaseDate", ""),
            "basePrice": pr.get("basePrice", 0),
            "popularity": popularity,
            "rating": rating,
            "reviewCount": int(popularity * 12) if rating else 0,
            "review": c.get("review", ""),
            "quickSpecs": p.get("quickSpecs", {}),
            "prices": pr.get("prices", []),
            "pros": c.get("pros", []),
            "cons": c.get("cons", []),
            "specs": p.get("specs", {}),
        })

    # merged.json is the clean source the prerenderer reads
    C.write_json("merged.json", {"brands": specs["brands"], "phones": merged, "news": news})

    out_path = os.path.join(C.HERE, "..", "js", "data.js")
    lines = [
        "/* AUTO-GENERATED by the PhoneHub pipeline (tools/build.py). Do not edit by hand. */",
        "window.BRANDS = " + json.dumps(specs["brands"], ensure_ascii=False, indent=2) + ";",
        'window.STORES = ["Amazon", "Flipkart", "Croma", "Reliance Digital", "Official Store"];',
        "window.PHONES = " + json.dumps(merged, ensure_ascii=False, indent=2) + ";",
        "window.NEWS = " + json.dumps(news, ensure_ascii=False, indent=2) + ";",
    ]
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    priced = sum(1 for m in merged if m["basePrice"])
    reviewed = sum(1 for m in merged if m["rating"])
    print(f"[build] wrote js/data.js — {len(merged)} phones "
          f"({reviewed} with AI reviews, {priced} with live prices)")

    # pre-render static phone pages, then regenerate sitemap.xml + robots.txt
    for mod_name in ("prerender", "gen_seo"):
        try:
            mod = __import__(mod_name)
            mod.main()
        except SystemExit:
            pass
        except Exception as e:  # noqa
            print(f"[build] {mod_name} skipped: {e}")


if __name__ == "__main__":
    main()
